### ISSUE TITLE
Names concatenating

### ISSUE THREAD

**Issue by IKKaybe** [dewster/lol-mastery-manager-new-client#1]
For example if I generate varus first - names the page - VarusTop but then if i go Annie next game it will name the page - VarusTop AnnieMid

**Comment by dewster** [comment]
hi, yep i know this probelm.. (and champ select screen name save 60% work.. client fail :/) 
next week fix to name probelem  :3 ty for feedback ^^_

**Comment by dewster** [comment]
Hi ^^ i fixed 😊
