### ISSUE TITLE
Doesn't work in Champ select with new patch 7.12

### ISSUE THREAD

**Issue by jpm1993** [dewster/lol-mastery-manager-new-client#3]

**Comment by dewster** [comment]
Hi ^^ I was upgraded yesterday so pls download new version. Link: https://github.com/dewster/lol-mastery-manager-new-client/releases/download/HOTFIX/LoLMasteryManagerSetup.msi

**Comment by jpm1993** [comment]
I did thank you !! I didn't see it thank you for the fix so fast

**Comment by dewster** [comment]
Np ^^  hf :3

**Comment by dewster** [comment]
hi.. update again.. riot update champ select coordinate.. link-> https://github.com/dewster/lol-mastery-manager-new-client/releases/download/1.2.2/LoLMasteryManagerSetup.msi
